In [1]:
#############NEW PRice and Volume########################
from nsepy import get_history
from datetime import datetime,date, timedelta
import pandas as pd
from pandas_datareader import data as pdr
import yfinance as yf
import datetime
from nsepy import get_history
data = pd.read_csv('ind_nifty50list.csv')

In [2]:
start = datetime.datetime.today() - timedelta(days = 180)
end = datetime.datetime.today()  - timedelta(days = 1)
if (end.weekday() == 0):
    start = start - timedelta(days = 2)
elif (end.weekday() == 6):
    end = end - timedelta(days = 2)
    start = end - timedelta(days = 179)
start = end - timedelta(days = 179)

In [4]:
import numpy as np
def moving_average(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w
#data = np.array([10,5,8,9,15,22,26,11,15,16,18,7])

In [ ]:
for i in range(len(data.iloc[:,2])):    
    historicalData = get_history(symbol = data.iloc[i,2], start=start, end=end)
    historicalData["Company"] = data.iloc[i,0]
    ma = moving_average(historicalData['Close'], 100)
    historicalData["MAV"] = (len(historicalData['Close'])-len(ma))*[0]+list(ma)
    for i, row in historicalData.iterrows():
        if i> datetime.date.today() - timedelta(days = 2) and row['MAV']<row['Close']:
            print(i,row['Company'],row['MAV'],row['Close'])

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
  
# define data values
x = np.array([1, 2, 3, 4])  # X-axis points
y = x*2  # Y-axis points
  
plt.plot(x, y)  # Plot the chart
plt.show()

In [2]:
import os
import pandas as pd
g = []
folder_path = 'C:/Users/018598/Desktop/FIle/'
for f in os.listdir(folder_path):
    data = pd.read_excel(folder_path+f, sheet_name=0)
    g.append(data)

In [3]:
pd.concat(g,ignore_index=True).to_excel(folder_path+'Compile.xlsx')

In [4]:
from nsepy import get_history
from datetime import datetime,date, timedelta
import pandas as pd
from pandas_datareader import data as pdr
import yfinance as yf
import datetime

data = pd.read_excel('Exchange.xlsx', 'PublicCompanies')

# Set the investment weights (I arbitrarily picked for example)
# weights = np.array([.25, .3, .15, .3])
# # Set an initial investment level
# initial_investment = 1000000
# # Download closing prices
# data = pdr.get_data_yahoo(tickers, start="2018-01-01", end=dt.date.today())['Close']
# #From the closing prices, calculate periodic returns
# returns = data.pct_change()
# returns.tail()

In [9]:
start = datetime.datetime.today() - timedelta(days = 9)
end = datetime.datetime.today()  - timedelta(days = 1)
if (end.weekday() == 0):
    start = start - timedelta(days = 2)
elif (end.weekday() == 6):
    end = end - timedelta(days = 2)
    start = end - timedelta(days = 8)
f1 = pd.DataFrame()
historicalData = get_history(symbol = data.iloc[1,2], start=start, end=end)
f1[i] = historicalData['Close']

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2023-02-03,BAJFINANCE,EQ,5717.65,5770.00,6030.00,5747.05,6000.0,6014.25,5901.96,1486892,8.775572e+14,136120,684457,0.4603
2023-02-06,BAJFINANCE,EQ,6014.25,6000.00,6124.00,5955.60,6108.0,6104.20,6050.64,1073820,6.497302e+14,113526,385557,0.3591
2023-02-07,BAJFINANCE,EQ,6104.20,6122.95,6182.00,6100.00,6154.0,6160.55,6151.91,1472193,9.056805e+14,105102,826932,0.5617
2023-02-08,BAJFINANCE,EQ,6160.55,6165.00,6377.00,6162.80,6335.2,6351.65,6287.28,1903208,1.196601e+15,155955,990336,0.5204
2023-02-09,BAJFINANCE,EQ,6351.65,6374.90,6487.80,6335.25,6462.0,6455.00,6439.66,1838154,1.183709e+15,136086,935521,0.5089
2023-02-10,BAJFINANCE,EQ,6455.00,6453.95,6527.60,6420.00,6441.0,6435.50,6473.96,1291282,8.359706e+14,111203,630400,0.4882
2023-02-13,BAJFINANCE,EQ,6435.50,6434.95,6473.15,6297.05,6344.0,6345.50,6358.19,736557,4.683171e+14,82444,284853,0.3867

In [ ]:
for i in range(0,len(data.iloc[0:4,2])):
    historicalData = get_history(symbol = data.iloc[i,2], start=start, end=end

In [6]:
type(data.iloc[0:4,2])

pandas.core.series.Series

In [ ]:
avg_rets.dot(weights)